/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PagamentoConcluidoRouteImport } from './routes/pagamento-concluido'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

const PagamentoConcluidoRoute = PagamentoConcluidoRouteImport.update({
  id: '/pagamento-concluido',
  path: '/pagamento-concluido',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pagamento-concluido': typeof PagamentoConcluidoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pagamento-concluido': typeof PagamentoConcluidoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/pagamento-concluido': typeof PagamentoConcluidoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/pagamento-concluido'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/pagamento-concluido'
  id: '__root__' | '/' | '/pagamento-concluido'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PagamentoConcluidoRoute: typeof PagamentoConcluidoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pagamento-concluido': {
      id: '/pagamento-concluido'
      path: '/pagamento-concluido'
      fullPath: '/pagamento-concluido'
      preLoaderRoute: typeof PagamentoConcluidoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PagamentoConcluidoRoute: PagamentoConcluidoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
